version: "3"
services:
  tinyproxy:
    image: drewgwallace/tinyproxy:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8888:8888"
